app/routes.php
<?php

Route::get('/', 'GuestController@index');
Route::get('datatable/books/borrow', array('as'=>'datatable.books.borrow', 'uses'=>'BooksController@borrowDatatable'));
Route::group(array('before' => 'auth'), function () {
    Route::get('dashboard', array('as'=>'dashboard', 'uses'=>'HomeController@dashboard'));
    Route::get('books', array('as'=>'member.books', 'uses'=>'MemberController@books'));
    Route::get('profile', array('as'=>'member.profile', 'uses'=>'MemberController@profile'));
    Route::get('profile/edit', array('as'=>'member.profile.edit', 'uses'=>'MemberController@editProfile'));
    Route::post('profile', array('as'=>'member.profile.update', 'uses'=>'MemberController@updateProfile'));
    Route::get('editpassword', array('as'=>'home.editpassword', 'uses'=>'HomeController@editPassword'));
    Route::post('updatepassword', array('as'=>'home.updatepassword', 'uses'=>'HomeController@updatePassword'));
    Route::get('books/{book}/borrow', array('as'=>'books.borrow', 'uses'=>'BooksController@borrow'));
    Route::get('books/{book}/return', array('as'=>'books.return', 'uses'=>'BooksController@returnBack'));
    Route::group(array('prefix' => 'admin', 'before' => 'admin'), function()
    {
        Route::resource('authors', 'AuthorsController');
        Route::get('books/export', array('as'=>'admin.books.export', 'uses'=>'BooksController@export'));
        Route::post('books/export-post', array('as'=>'admin.books.exportpost', 'uses'=>'BooksController@exportPost'));
        Route::get('books/template', array('as'=>'admin.books.template', 'uses'=>'BooksController@generateExcelTemplate'));
        Route::post('books/import', array('as'=>'admin.books.import', 'uses'=>'BooksController@importExcel'));
        Route::resource('books', 'BooksController');
        Route::resource('users', 'UsersController');
        Route::get('borrow', array('as'=>'admin.borrow', 'uses'=>'BorrowController@index'));
        Route::get('borrow/return/{id}', array('as'=>'admin.borrow.return', 'uses'=>'BorrowController@returnBack'));
    });
});
Route::get('login', array('as'=>'guest.login', 'uses'=>'GuestController@login'));
Route::post('authenticate', 'HomeController@authenticate');
Route::get('logout', 'HomeController@logout');
Route::get('signup', array('as'=>'guest.signup', 'uses'=>'GuestController@signup'));
Route::post('register', array('as'=>'guest.register', 'uses'=>'GuestController@register'));
Route::get('activate', array('as'=>'user.activate', 'uses'=>'GuestController@activate'));
Route::get('forgot', array('as'=>'guest.forgot', 'uses'=>'GuestController@forgotPassword'));
Route::post('sendresetcode', array('as'=>'guest.sendresetcode', 'uses'=>'GuestController@sendResetCode'));
Route::get('reset', array('as'=>'guest.createnewpassword', 'uses'=>'GuestController@createNewPassword'));
Route::post('reset', array('as'=>'guest.storenewpassword', 'uses'=>'GuestController@storeNewPassword'));

?>

app/models/Author.php
<?php

class Author extends BaseModel {

	// Add your validation rules here
	public static $rules = [
		'name' => 'required|unique:authors,name,:id'
	];

	// Don't forget to fill this array
	protected $fillable = ['name'];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        self::deleting(function($author)
        {
            // mengecek apakah penulis masih punya buku
            if ($author->books->count() > 0) {
                $html = 'Penulis tidak bisa dihapus karena masih memiliki buku : ';
                $html .= '<ul>';
                foreach ($author->books as $book) {
                    $html .= "<li>$book->title</li>";
                }
                $html .= '</ul>';
                Session::flash('errorMessage', $html);
                return false;
            }
        });
    }

    /**
     * Relasi One-to-Many dengan model Book
     * @return Collection
     */
    public function books()
    {
        return $this->hasMany('Book');
    }

}

app/controllers/AuthorsController.php
<?php

class AuthorsController extends \BaseController {

	/**
	 * Display a listing of authors
	 *
	 * @return Response
	 */
	public function index()
	{
		 if(Datatable::shouldHandle())
	    {
	        return Datatable::collection(Author::all(array('id','name')))
	            ->showColumns('id', 'name')
	            ->addColumn('', function ($model) {
                    $html = '<a href="'.route('admin.authors.edit', ['authors'=>$model->id]).'" class="uk-button uk-button-small uk-button-link">edit</a> ';
                    $html .= Form::open(array('url' => route('admin.authors.destroy', ['authors'=>$model->id]), 'method'=>'delete', 'class'=>'uk-display-inline'));
					$html .= Form::submit('delete', array('class' => 'uk-button uk-button-small'));
					$html .= Form::close();
					return $html;
                })
	            ->searchColumns('name')
	            ->orderColumns('name')
	            ->make();
	    }
		return View::make('authors.index')->withTitle('Penulis');
	}

	/**
	 * Show the form for creating a new author
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('authors.create')->withTitle('Tambah Penulis');
	}

	/**
	 * Store a newly created author in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make($data = Input::all(), Author::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		$author = Author::create($data);

		return Redirect::route('admin.authors.index')->with("successMessage", "Berhasil menyimpan $author->name ");
	}

	/**
	 * Display the specified author.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$author = Author::findOrFail($id);

		return View::make('authors.show', compact('author'));
	}

	/**
	 * Show the form for editing the specified author.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$author = Author::find($id);

		return View::make('authors.edit', ['author'=>$author])->withTitle("Ubah $author->name");
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$author = Author::findOrFail($id);

		$validator = Validator::make($data = Input::all(), $author->updateRules());

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		$author->update($data);

		return Redirect::route('admin.authors.index')->with("successMessage", "Berhasil menyimpan $author->name ");
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		// mengecek apakah author bisa dihapus
		if (!Author::destroy($id))
		{
			return Redirect::back();
		}

		return Redirect::route('admin.authors.index')->with('successMessage', 'Penulis berhasil dihapus.');
	}

}

app/views/authors/_form.blade.php
<div class="uk-form-row">
    {{ Form::labelUk('name', 'Nama Penulis') }}
    {{ Form::textUk('name', 'Nama Penulis', 'uk-icon-user') }}
</div>
{{ HTML::divider() }}
<div class="uk-form-row">
    {{ Form::submitUk('Simpan') }}
</div>

app/views/authors/create.blade.php
@extends('layouts.master')

@section('title')
    {{ $title }}
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li><a href="{{ route('admin.authors.index') }}">Penulis</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')
    {{ Form::open(array('url' => route('admin.authors.store'), 'method' => 'post', 'class'=>'uk-form uk-form-horizontal')) }}
        @include('authors._form')
    {{ Form::close() }}
@stop

app/views/authors/edit.blade.php
@extends('layouts.master')

@section('title')
    {{ $title }}
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li><a href="{{ route('admin.authors.index') }}">Penulis</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')
    {{ Form::model($author, array('url' => route('admin.authors.update', ['authors'=>$author->id]), 'method' => 'put', 'class'=>'uk-form uk-form-horizontal')) }}
        @include('authors._form')
    {{ Form::close() }}
@stop

app/views/authors/index.blade.php
@extends('layouts.master')

@section('asset')
    @include('layouts.partials.datatable')
@stop

@section('title')
    {{ $title }}
@stop

@section('title-button')
    {{ HTML::buttonAdd() }}
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')

    {{ Datatable::table()
    ->addColumn('id','Nama', '')       // these are the column headings to be shown
    ->setOptions('aoColumnDefs',array(
        array(
            'bVisible' => false,
            'aTargets' => [0]),
        array(
            'sTitle' => 'Nama',
            'aTargets' => [1]),
        array(
            'bSortable' => false,
            'aTargets' => [2])
        ))
    ->setOptions('bProcessing', true)
    ->setUrl(route('admin.authors.index'))   // this is the route where data will be retrieved
    ->render('datatable.uikit') }}

@stop

app/views/authors/show.blade.php
/Users/rahmatawaludin/Sites/larapus/app/views/authors/show.blade.php