app/routes.php
<?php

Route::get('/', 'GuestController@index');
Route::get('datatable/books/borrow', array('as'=>'datatable.books.borrow', 'uses'=>'BooksController@borrowDatatable'));
Route::group(array('before' => 'auth'), function () {
    Route::get('dashboard', array('as'=>'dashboard', 'uses'=>'HomeController@dashboard'));
    Route::get('books', array('as'=>'member.books', 'uses'=>'MemberController@books'));
    Route::get('profile', array('as'=>'member.profile', 'uses'=>'MemberController@profile'));
    Route::get('profile/edit', array('as'=>'member.profile.edit', 'uses'=>'MemberController@editProfile'));
    Route::post('profile', array('as'=>'member.profile.update', 'uses'=>'MemberController@updateProfile'));
    Route::get('editpassword', array('as'=>'home.editpassword', 'uses'=>'HomeController@editPassword'));
    Route::post('updatepassword', array('as'=>'home.updatepassword', 'uses'=>'HomeController@updatePassword'));
    Route::get('books/{book}/borrow', array('as'=>'books.borrow', 'uses'=>'BooksController@borrow'));
    Route::get('books/{book}/return', array('as'=>'books.return', 'uses'=>'BooksController@returnBack'));
    Route::group(array('prefix' => 'admin', 'before' => 'admin'), function()
    {
        Route::resource('authors', 'AuthorsController');
        Route::get('books/export', array('as'=>'admin.books.export', 'uses'=>'BooksController@export'));
        Route::post('books/export-post', array('as'=>'admin.books.exportpost', 'uses'=>'BooksController@exportPost'));
        Route::get('books/template', array('as'=>'admin.books.template', 'uses'=>'BooksController@generateExcelTemplate'));
        Route::post('books/import', array('as'=>'admin.books.import', 'uses'=>'BooksController@importExcel'));
        Route::resource('books', 'BooksController');
        Route::resource('users', 'UsersController');
        Route::get('borrow', array('as'=>'admin.borrow', 'uses'=>'BorrowController@index'));
        Route::get('borrow/return/{id}', array('as'=>'admin.borrow.return', 'uses'=>'BorrowController@returnBack'));
    });
});
Route::get('login', array('as'=>'guest.login', 'uses'=>'GuestController@login'));
Route::post('authenticate', 'HomeController@authenticate');
Route::get('logout', 'HomeController@logout');
Route::get('signup', array('as'=>'guest.signup', 'uses'=>'GuestController@signup'));
Route::post('register', array('as'=>'guest.register', 'uses'=>'GuestController@register'));
Route::get('activate', array('as'=>'user.activate', 'uses'=>'GuestController@activate'));
Route::get('forgot', array('as'=>'guest.forgot', 'uses'=>'GuestController@forgotPassword'));
Route::post('sendresetcode', array('as'=>'guest.sendresetcode', 'uses'=>'GuestController@sendResetCode'));
Route::get('reset', array('as'=>'guest.createnewpassword', 'uses'=>'GuestController@createNewPassword'));
Route::post('reset', array('as'=>'guest.storenewpassword', 'uses'=>'GuestController@storeNewPassword'));

?>

app/models/Book.php
<?php

class Book extends BaseModel {

	// Add your validation rules here
	public static $rules = [
		'title' => 'required|unique:books,title,:id',
        'author_id' => 'required|exists:authors,id',
        'amount'=> 'numeric',
        'cover' => 'image|max:2048'
	];

	// Don't forget to fill this array
	protected $fillable = ['title','author_id','amount'];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        self::updating(function($book)
        {
            $borrowed = DB::table('book_user')
                ->where('book_id', $book->id)
                ->where('returned', 0)
                ->count();
            if ($book->amount < $borrowed) {
                Session::flash('errorMessage', "Jumlah buku $book->title harus >= $borrowed");
                return false;
            }
        });

        self::deleting(function($book)
        {
            $borrowed = DB::table('book_user')
                ->where('book_id', $book->id)
                ->where('returned', 0)
                ->count();
            if ($borrowed > 0) {
                Session::flash('errorMessage', "Buku $book->title masih dipinjam.");
                return false;
            }
        });
    }

    /**
     * Custom attributes
     * @var array
     */
    protected $appends = ['stock'];

    /**
     * Accessor for stock attribute
     * @return int
     */
    public function getStockAttribute()
    {
        $borrowed =  DB::table('book_user')
            ->where('book_id', $this->id)
            ->where('returned', 0)
            ->count();
        $stock = $this->amount - $borrowed;
        return $stock;
    }

    /**
     * Kebalikan relasi One-to-Many relation dengan model Author
     * @return Author
     */
    public function author()
    {
        return $this->belongsTo('Author');
    }

    /**
     * Relasi pivot (Many-to-Many) dengan User
     * @return Collection
     */
    public function users()
    {
        return $this->belongsToMany('User')->withPivot('returned')->withTimestamps();
    }

    /**
     * Attach current user id to book->users
     * @return response
     */
    public function borrow()
    {
        $user = Sentry::getUser();

        // cek apakah buku ini sedang dipinjam oleh user
        if($user->books()->wherePivot('book_id',$this->id)->wherePivot('returned', 0)->count() > 0 ) {
            throw new BookAlreadyBorrowedException("Buku $this->title sedang Anda pinjam.");
        }

        if($this->stock == 0) {
            throw new BookOutOfStockException("Buku $this->title sudah tidak tersedia.");
        }

        return $this->users()->attach($user);
    }

    public function returnBack()
    {
        $user = Sentry::getUser();
        DB::table('book_user')
            ->where('book_id', $this->id)
            ->where('user_id', $user->id)
            ->where('returned', 0)
            ->update(array(
                'returned' => 1,
                'updated_at' => $this->freshTimestamp()
            ));
    }

}

app/controllers/BooksController.php
<?php

class BooksController extends \BaseController {

	/**
	 * Instantiate a new BooksController
	 */
	public function __construct()
	{
		// Letakan filter regularUser sebelum memanggil fungsi borrow
        $this->beforeFilter('regularUser', array( 'only' => array('borrow') ) );

        // CSRF filter sebelum method destroy
		$this->beforeFilter('csrf', array( 'only' => array('destroy') ) );
	}

	/**
	 * Display a listing of books
	 *
	 * @return Response
	 */
	public function index()
	{
		if(Datatable::shouldHandle())
	    {
	    	// eager load author untuk menghemat query sql
	        return Datatable::collection(Book::with('author')->get())
	            ->showColumns('id', 'title', 'amount', 'stock')
	            // menggunakan closure untuk menampilkan nama penulis dari relasi
	            ->addColumn('author', function ($model) {
                    return $model->author->name;
                })
	            ->addColumn('', function ($model) {
                    $html = '<a href="'.route('admin.books.edit', ['books'=>$model->id]).'" class="uk-button uk-button-small uk-button-link">edit</a> ';
                    $html .= Form::open(array('url' => route('admin.books.destroy', ['books'=>$model->id]), 'method'=>'delete', 'class'=>'uk-display-inline'));
					$html .= Form::submit('delete', array('class' => 'uk-button uk-button-small'));
					$html .= Form::close();
					return $html;
                })
	            ->searchColumns('title', 'amount', 'author')
	            ->orderColumns('title', 'amount', 'author')
	            ->make();
	    }
		return View::make('books.index')->withTitle('Buku');
	}

	/**
	 * Show the form for creating a new book
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('books.create')->withTitle('Tambah Buku');
	}

	/**
	 * Store a newly created book in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make($data = Input::all(), Book::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		$book = Book::create(Input::except('cover'));

        // isi field cover jika ada cover yang diupload
        if (Input::hasFile('cover')) {
            $uploaded_cover = Input::file('cover');

            // mengambil extension file
            $extension = $uploaded_cover->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';

            // memindahkan file ke folder public/img
            $uploaded_cover->move($destinationPath, $filename);

            // mengisi field cover di book dengan filename yang baru dibuat
            $book->cover = $filename;
            $book->save();
        }

		return Redirect::route('admin.books.index')->with("successMessage", "Berhasil menyimpan $book->title ");;
	}

	/**
	 * Display the specified book.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$book = Book::findOrFail($id);

		return View::make('books.show', compact('book'));
	}

	/**
	 * Show the form for editing the specified book.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$book = Book::find($id);

		return View::make('books.edit', ['book'=>$book])->withTitle("Ubah $book->title");
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$book = Book::findOrFail($id);

		$validator = Validator::make(Input::all(), $book->updateRules());

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

        if (Input::hasFile('cover')) {
            $filename = null;
            $uploaded_cover = Input::file('cover');
            $extension = $uploaded_cover->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';

            // memindahkan file ke folder public/img
            $uploaded_cover->move($destinationPath, $filename);

            // hapus cover lama, jika ada
            if ($book->cover) {
                $old_cover = $book->cover;
                $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                    . DIRECTORY_SEPARATOR . $book->cover;

                try {
                    File::delete($filepath);
                } catch (FileNotFoundException $e) {
                    // File sudah dihapus/tidak ada
                }
            }

            // ganti field cover dengan cover yang baru
            $book->cover = $filename;
            $book->save();
        }

		if (!$book->update(Input::except('cover'))) {
            return Redirect::back();
        }

		return Redirect::route('admin.books.index')->with("successMessage", "Berhasil menyimpan $book->title. ");
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		if (!Book::destroy($id)) {
            return Redirect::back();
        }

        if (Request::ajax()) {
            return Response::json(array('id' => $id));
        }

		return Redirect::route('admin.books.index')->with('successMessage', 'Buku berhasil dihapus.');
	}

	/**
	 * Borrow book
	 * @param  int $id book id
	 * @return response
	 */
	public function borrow($id)
	{
		$book = Book::findOrFail($id);

		try {
			$book->borrow();
		} catch (BookException $e) {
			return Redirect::back()->with('errorMessage', $e->getMessage());
		}

		return Redirect::back()->with("successMessage", "Anda telah meminjam $book->title");
	}

	/**
	 * Get datatable for books borrow
	 * @return json
	 */
	public function borrowDatatable()
    {
        // eager load author untuk menghemat query sql
        return Datatable::collection(Book::with('author')->get())
            ->showColumns('id', 'title', 'amount', 'stock')
            // menggunakan closure untuk menampilkan nama penulis dari relasi
            ->addColumn('author', function ($model) {
                return $model->author->name;
            })
            // menggunakan helper untuk membuat link
            ->addColumn('', function ($model) {
                return link_to_route('books.borrow', 'Pinjam', ['book'=>$model->id]);
            })
            ->searchColumns('title', 'amount', 'author')
            ->orderColumns('title', 'amount', 'author')
            ->make();
    }

    /**
     * Return specified book
     * @param  int $id book id
     * @return response
     */
    public function returnBack($id)
    {
    	$book = Book::findOrFail($id);
    	$book->returnBack();
    	return Redirect::back()->with("successMessage", "Anda telah mengembalikan $book->title.");
    }

    /**
     * Tampilkan halaman untuk export excel
     * @return response
     */
    public function export()
    {
        return View::make('books.export')->withTitle('Export Buku');
    }

    /**
     * Download excel data buku
     * @return PHPExcel
     */
    public function exportPost()
    {
        // validasi
        $rules = ['author_id'=>'required', 'type'=>'required'];
        $messages = ['author_id.required'=>'Anda belum memilih penulis. Pilih minimal 1 penulis.'];
        $validator = Validator::make(Input::all(), $rules, $messages);
        if ($validator->fails())
        {
            return Redirect::back()->withErrors($validator);
        }

        $books = Book::whereIn('id', Input::get('author_id'))->get();

        $type = Input::get('type');
        switch ($type) {
            case 'xls':
                return $this->exportExcel($books);
                break;

            case 'pdf':
                return $this->exportPdf($books);
                break;

            default:
                break;
        }
    }

    /**
     * Download excel data buku
     * @return PHPExcel
     */
    private function exportExcel($books)
    {
        Excel::create('Data Buku Larapus', function($excel) use ($books) {
            // Set the properties
            $excel->setTitle('Data Buku Larapus')
                  ->setCreator('Rahmat Awaludin');

            $excel->sheet('Data Buku', function($sheet) use ($books) {
                $row = 1;
                $sheet->row($row, array(
                    'Judul',
                    'Jumlah',
                    'Stok',
                    'Penulis'
                ));
                foreach ($books as $book) {
                   $sheet->row(++$row, array(
                    $book->title,
                    $book->amount,
                    $book->stock,
                    $book->author->name
                ));
                }
            });
        })->export('xls');
    }

    /**
     * Download pdf data buku
     * @return Dompdf
     */
    private function exportPdf($books)
    {
        $data['books'] = $books;
        $pdf = PDF::loadView('pdf.books', $data);
        return $pdf->download('books.pdf');
    }

    /**
     * Generate template excel untuk import buku
     * @return PHPExcel
     */
    public function generateExcelTemplate()
    {
        Excel::create('Template Import Buku', function($excel) {
            // Set the properties
            $excel->setTitle('Template Import Buku')
                  ->setCreator('Larapus')
                  ->setCompany('Larapus')
                  ->setDescription('Template import buku untuk Larapus');

            $excel->sheet('Data Buku', function($sheet) {
                $row = 1;
                $sheet->row($row, array(
                    'Judul',
                    'Penulis',
                    'Jumlah'
                ));
            });

        })->export('xls');
    }

    /**
     * Import excel dan simpan ke database

app/views/books/_borrowdatatable.blade.php
{{ Datatable::table()
    ->addColumn('id','title', 'author', 'amount', 'stock', '')
    ->setOptions('aoColumnDefs',array(
        array(
            'bVisible' => false,
            'aTargets' => [0]),
        array(
            'sTitle' => 'Judul',
            'aTargets' => [1]),
        array(
            'sTitle' => 'Jumlah',
            'aTargets' => [2]),
        array(
            'sTitle' => 'Stok',
            'aTargets' => [3]),
        array(
            'sTitle' => 'Penulis',
            'aTargets' => [4]),
        array(
            'bSortable' => false,
            'aTargets' => [5])
        ))
    ->setOptions('bProcessing', true)
    ->setUrl(route('datatable.books.borrow'))
    ->render('datatable.uikit') }}

app/views/books/_form.blade.php
<div class="uk-form-row">
    {{ Form::labelUk('title', 'Judul') }}
    {{ Form::textUk('title', 'Judul Buku', 'uk-icon-book') }}
</div>
<div class="uk-form-row">
    {{ Form::labelUk('author_id', 'Penulis') }}
    {{ Form::select('author_id', array(''=>'')+Author::lists('name','id'), null, array(
                        'id'=>'author_id',
                        'placeholder' => "Pilih Penulis")) }}
</div>
<div class="uk-form-row">
    {{ Form::labelUk('amount', 'Jumlah') }}
    {{ Form::textUk('amount', 'Jumlah Buku', 'uk-icon-unsorted') }}
</div>

<div class="uk-form-row">
    {{ Form::labelUk('cover', 'Cover') }}
    <div class="form-controls">
        {{ Form::file('cover') }}
        @if (isset($book) && $book->cover)
            <p>
            {{ HTML::image(asset('img/'.$book->cover), null, ['class'=>'uk-thumbnail-medium']) }}
            </p>
        @endif
    </div>
</div>



{{ HTML::divider() }}
<div class="uk-form-row">
    {{ Form::submitUk('Simpan') }}
</div>
<script>
    $(document).ready(function() {
        $("#author_id").select2();
    });
</script>

app/views/books/_import.blade.php
<div class="uk-form-row">
    {{ Form::labelUk('template', 'Gunakan template terbaru') }}
    <a class="uk-button uk-button-small uk-button-success" href="{{ route('admin.books.template') }}"><i class="uk-icon-cloud-download"></i> Download</a>
</div>

<div class="uk-form-row">
    {{ Form::labelUk('excel', 'Pilih file') }}
    <div class="form-controls">
        {{ Form::file('excel') }}
    </div>
</div>

{{ HTML::divider() }}
<div class="uk-form-row">
    {{ Form::submitUk('Import') }}
</div>

app/views/books/borrow.blade.php
@extends('layouts.master')

@section('asset')
    @include('layouts.partials.datatable')
@stop

@section('title')
    {{ $title }}
@stop

@section('content')
    @include('books._borrowdatatable')
@stop

app/views/books/create.blade.php
@extends('layouts.master')

@section('title')
    {{ $title }}
@stop

@section('asset')
    @include('layouts.partials.select2')
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li><a href="{{ route('admin.books.index') }}">Buku</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')
    <!-- Navigasi dengan tab untuk memilih cara input buku -->
    <ul class="uk-tab" data-uk-tab="{connect:'#tambahbuku'}">
        <li class="uk-active"><a href="#"><i class="uk-icon-pencil-square-o"></i> Isi Form</a></li>
        <li ><a href="#"><i class="uk-icon-cloud-upload"></i> Upload Excel</a></li>
    </ul>

    <!-- Container dari isian tab -->
    <ul id="tambahbuku" class="uk-switcher uk-margin">
        <li>
            {{ Form::open(array('url' => route('admin.books.store'), 'method' => 'post', 'files'=>'true', 'class'=>'uk-form uk-form-horizontal')) }}
                @include('books._form')
            {{ Form::close() }}
        </li>
        <li>
            {{ Form::open(array('url' => route('admin.books.import'), 'method' => 'post', 'files'=>'true', 'class'=>'uk-form uk-form-horizontal')) }}
                @include('books._import')
            {{ Form::close() }}
        </li>
    </ul>
@stop

app/views/books/edit.blade.php
@extends('layouts.master')

@section('title')
    {{ $title }}
@stop

@section('asset')
    @include('layouts.partials.select2')
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li><a href="{{ route('admin.books.index') }}">Buku</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')
    {{ Form::model($book, array('url' => route('admin.books.update', ['books'=>$book->id]), 'files' => 'true', 'method' => 'put', 'class'=>'uk-form uk-form-horizontal')) }}
        @include('books._form')
    {{ Form::close() }}
@stop

app/views/books/export.blade.php
@extends('layouts.master')

@section('title')
    {{ $title }}
@stop

@section('asset')
    @include('layouts.partials.select2')
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li><a href="{{ route('admin.books.index') }}">Buku</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')
    {{ Form::open(array('url' => route('admin.books.exportpost'), 'method' => 'post', 'class'=>'uk-form uk-form-horizontal')) }}
        <div class="uk-form-row">
            {{ Form::labelUk('author_id', 'Pilih Penulis') }}
            {{ Form::select('author_id[]', []+Author::lists('name','id'), null, array(
                    'multiple',
                    'id'=>'author_id',
                    'placeholder' => "Pilih Penulis",
                    'style'=>'width:20%')) }}
        </div>

        <div class="uk-form-row">
            {{ Form::labelUk('type', 'Pilih Output') }}
            {{ Form::radio('type', 'xls', true) }} Excel
            {{ Form::radio('type', 'pdf') }} PDF
        </div>

        {{ HTML::divider() }}
        <div class="uk-form-row">
            {{ Form::submitUk('Download') }}
        </div>
    {{ Form::close() }}

    <script>
        $(document).ready(function() {
            $("#author_id").select2({placeholder: 'Pilih Penulis', allowClear: true});
        });
    </script>
@stop

app/views/books/import-review.blade.php
@extends('layouts.master')

@section('title')
    {{ $title }}
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li><a href="{{ route('admin.books.index') }}">Buku</a></li>
    <li><a href="{{ route('admin.books.create') }}">Tambah Buku</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')
    <a href="{{ route('admin.books.index')}}" class="uk-button uk-button-success">
        <i class="uk-icon-check"></i> Selesai
    </a>
    <table class="uk-table uk-table-hover">
        <thead>
            <tr>
                <th>Judul</th>
                <th>Penulis</th>
                <th>Jumlah</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($books as $book)
                <tr>
                    <td>{{ $book->title }}</td>
                    <td>{{ $book->author->name }}</td>
                    <td>{{ $book->amount }}</td>
                    <td>
                    {{ Form::open(array('url' => route('admin.books.destroy', ['books'=>$book->id]), 'id'=>'form-'.$book->id, 'method'=>'delete', 'class'=>'uk-display-inline review-delete')) }}
                        {{ Form::submit('delete', array('class' => 'uk-button uk-button-small uk-button-danger')) }}
                    {{ Form::close() }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <a href="{{ route('admin.books.index')}}" class="uk-button uk-button-success">
        <i class="uk-icon-check"></i> Selesai
    </a>
@stop

@section('pagejs')
    <script>
    $(function() {
        $('form.review-delete').on('click', function() {
            // disable behaviour default dari tombol submit
            event.preventDefault();
            // hapus data buku dengan ajax
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                dataType: 'json',
                data: {
                    _method : 'DELETE',
                    _token : $( this ).children( 'input[name=_token]' ).val()
                }
            }).done(function(data) {
                // cari baris yang dihapus
                baris = $('#form-'+data.id).closest('tr');
                // hilangkan baris (fadeout kemudian remove)
                baris.fadeOut(300, function() {$(this).remove()});
            });
        })
    });
    </script>
@stop

app/views/books/index.blade.php
@extends('layouts.master')

@section('asset')
    @include('layouts.partials.datatable')
@stop

@section('title')
    {{ $title }}
@stop

@section('title-button')
    {{ HTML::buttonAdd() }}
    <a class="uk-button uk-button-primary" href="{{ route('admin.books.export') }}">Export</a>
@stop

@section('breadcrumb')
    <li><a href="/">Dashboard</a></li>
    <li class="uk-active">{{ $title }}</li>
@stop

@section('content')

    {{ Datatable::table()
    ->addColumn('id','title', 'author', 'amount', 'stock', '')
    ->setOptions('aoColumnDefs',array(
        array(
            'bVisible' => false,
            'aTargets' => [0]),
        array(
            'sTitle' => 'Judul',
            'aTargets' => [1]),
        array(
            'sTitle' => 'Jumlah',
            'aTargets' => [2]),
        array(
            'sTitle' => 'Stok',
            'aTargets' => [3]),
        array(
            'sTitle' => 'Penulis',
            'aTargets' => [4]),
        array(
            'bSortable' => false,
            'aTargets' => [5])
        ))
    ->setOptions('bProcessing', true)
    ->setUrl(route('admin.books.index'))   // this is the route where data will be retrieved
    ->render('datatable.uikit') }}

@stop

app/views/books/show.blade.php
/Users/rahmatawaludin/Sites/larapus/app/views/books/show.blade.php